name: Pansentials
version: ${pom.version}

description: Pandora replacement for Essentials

main: au.com.addstar.pansentials.MasterPlugin

permissions:
  pansentials.command:
    default: op
  pansentials.fly:
    default: op
  pansentials.fly.other:
    default: op
  pansentials.fly.join:
    default: false
  pansentials.fly.changeworld:
    default: false
  pansentials.fly.safelogin:
    default: op
  
  pansentials.hat:
    default: op
    
  pansentials.workbench:
    default: op
    
  pansentials.heal:
    default: op
  pansentials.heal.other:
    default: op
  pansentials.feed:
    default: op
  pansentials.feed.other:
    default: op
    
  pansentials.speed:
    default: op
  pansentials.speed.other:
    default: op

  pansentials.exp:
    default: op
  
  pansentials.whois:
    default: op
    
  pansentials.dropitem:
    default: op
    
  pansentials.enchant:
    default: op
  pansentials.enchant.unsafe:
    default: op
    
  pansentials.more:
    default: op
    
  pansentials.repair:
    default: op
    
  pansentials.gamemode.*:
    children:
      pansentials.gamemode: true
      pansentials.gamemode.survival: true
      pansentials.gamemode.survival.other: true
      pansentials.gamemode.adventure: true
      pansentials.gamemode.adventure.other: true
      pansentials.gamemode.creative: true
      pansentials.gamemode.creative.other: true
  pansentials.gamemode:
    default: op
  pansentials.gamemode.survival:
    default: op
  pansentials.gamemode.survival.other:
    default: op
  pansentials.gamemode.adventure:
    default: op
  pansentials.gamemode.adventure.other:
    default: op
  pansentials.gamemode.creative:
    default: op
  pansentials.gamemode.creative.other:
    default: op
  
  pansentials.god:
    default: op
  pansentials.god.other:
    default: op

  pansentials.time:
    default: op
  pansentials.time.set:
    default: op
  
  pansentials.smite:
    default: op
    
commands:
  pansentials:
    usage: /<command>
    permission: pansentials.command
  fly:
    usage: /<command> [player]
    permission: pansentials.fly
  hat:
    usage: /<command>
    permission: pansentials.hat
  workbench:
    usage: /<command>
    permission: pansentials.workbench
    aliases: [wb, craft]
  feed:
    usage: /<command> [player]
    permission: pansentials.feed
  heal:
    usage: /<command> [player]
    permission: pansentials.heal
  speed:
    usage: /<command> [player] <speed/fly/walk> [speed]
    permission: pansentials.speed
  exp:
    usage: /<command> [player] OR /<command> <set|give> <player> <amount|L<level>>
    permission: pansentials.exp
    aliases: [xp]
  whois:
    usage: /<command> <player>
    permission: pansentials.whois
  dropitem:
    usage: /<command>
    permission: pansentials.dropitem
    aliases: [di, drop]
  enchant:
    usage: /<command> <enchantment> <level> [unsafe]
    permission: pansentials.enchant
  gamemode:
    usage: /<command> <gamemode> [player]
    permission: pansentials.gamemode
    aliases: [gm, gma, gmc, gms]
  more:
    usage: /<command> [amount]
    permission: pansentials.more
  repair:
    usage: /<command>
    permission: pansentials.repair
  god:
    usage: /<command> [player]
    permission: pansentials.god
    aliases: [ungod]
  time:
    usage: /<command> [world] [time]
    permission: pansentials.time
  smite:
    usage: /<command> [player] [effect]
    permission: pansentials.smite
    aliases: [schmite]